"""从零构建本地 Coding Agent 的教学实现。"""

from pi_agent_from_zero.agent import Agent, AgentRunError
from pi_agent_from_zero.coding_tools import (
    ProjectWorkspace,
    create_coding_tools,
    create_edit_tool,
    create_grep_tool,
    create_read_tool,
    create_write_tool,
)
from pi_agent_from_zero.events import (
    AgentCompleted,
    AgentEvent,
    AgentFailed,
    AgentStarted,
    AssistantCompleted,
    CancellationRequested,
    CancellationToken,
    DeadlineExceeded,
    ProviderCompleted,
    ProviderEvent,
    ProviderFailed,
    ProviderTextDelta,
    TextDeltaEvent,
    ToolCompleted,
    ToolStarted,
)
from pi_agent_from_zero.messages import (
    AssistantMessage,
    Message,
    ToolCall,
    ToolResultMessage,
    UserMessage,
)
from pi_agent_from_zero.providers import FakeModel, ModelRequest, Provider
from pi_agent_from_zero.tools import (
    OutputLimits,
    SchemaDefinitionError,
    SchemaValidationError,
    Tool,
    ToolDefinition,
    ToolExecutionError,
    ToolOutcome,
    ToolRegistry,
    create_bash_tool,
    truncate_output,
    validate_arguments,
)

__all__ = [
    "Agent",
    "AgentCompleted",
    "AgentEvent",
    "AgentFailed",
    "AgentRunError",
    "AgentStarted",
    "AssistantMessage",
    "AssistantCompleted",
    "CancellationRequested",
    "CancellationToken",
    "DeadlineExceeded",
    "FakeModel",
    "Message",
    "ModelRequest",
    "OutputLimits",
    "ProjectWorkspace",
    "Provider",
    "ProviderCompleted",
    "ProviderEvent",
    "ProviderFailed",
    "ProviderTextDelta",
    "TextDeltaEvent",
    "Tool",
    "ToolCall",
    "ToolResultMessage",
    "ToolCompleted",
    "ToolDefinition",
    "ToolExecutionError",
    "ToolOutcome",
    "ToolRegistry",
    "ToolStarted",
    "UserMessage",
    "SchemaDefinitionError",
    "SchemaValidationError",
    "__version__",
    "create_bash_tool",
    "create_coding_tools",
    "create_edit_tool",
    "create_grep_tool",
    "create_read_tool",
    "create_write_tool",
    "truncate_output",
    "validate_arguments",
]

__version__ = "0.5.0"
